language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure sdqsdq
sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio update

script:
    - platformio run -e <uno>